language: php

php:
  - '7.2'
  - '7.3'

services:
  - mysql

addons:
  chrome: stable

before_install:
  - mysql -e 'CREATE DATABASE libra;'

install:
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk
