name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
      STRIPE_PRODUCT: ${{ secrets.STRIPE_PRODUCT }}
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: cp .env.ci .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Create Database
      run: touch database/database.sqlite
    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver 79
    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit
    - name: Run Dusk Tests
      run: php artisan dusk
